#!/usr/bin/env bash

# Why this file, you ask? Because lazy.

cd ~/my-awesome-macosx-ansible-setup
vim .
git commit -a

# This is *kind* of silly - it should be replaced by asking whether to run the configuration again.
configure "$@"
